import Icon from './Icon'
const services = [
 ['01', 'Responsive Web Development', 'Build websites that adapt cleanly from mobile screens to desktop layouts, without losing clarity or usability.', 'HTML · CSS · JavaScript', 'A dependable web presence for every visitor and device.'],
 ['02', 'Landing Page Development', 'Create focused pages that communicate an offer clearly and guide visitors toward a meaningful next action.', 'React · Responsive Design · UI', 'A more direct path from first impression to enquiry or action.'],
 ['03', 'React Web Applications', 'Develop component-based interfaces that are organized, maintainable, and ready for product features to grow.', 'React · JavaScript · Git', 'A practical frontend foundation for evolving ideas.'],
 ['04', 'UI Implementation', 'Turn designs and requirements into precise, responsive screens while keeping interaction and accessibility in view.', 'CSS · Components · Responsive UI', 'Interfaces that remain true to the intended experience.'],
 ['05', 'API Integration', 'Connect frontend interfaces to APIs and present data in clear, useful states for the people using the product.', 'JavaScript · React · APIs', 'Product information that feels connected and understandable.'],
 ['06', 'Website Optimization', 'Refine layout, responsiveness, and interaction details in existing pages to reduce friction and improve polish.', 'CSS · UI Review · Performance', 'A more cohesive, easier-to-use website.']
]
export default function Services() { return <section id="services" className="section service-section"><div className="container"><div className="section-heading reveal"><div><p className="overline">How I can help</p><h2>Built around the<br/><em>outcome you need.</em></h2></div><p>Whether you're defining a new web presence or refining an existing product, I bring a practical frontend lens to the work.</p></div><div className="services-list">{services.map(([num,title,description,tech,benefit]) => <article className="service reveal" key={title}><span className="service-num">{num}</span><div><h3>{title}</h3><p>{description}</p></div><div className="service-meta"><span>{tech}</span><strong><Icon name="arrow" size={15}/>{benefit}</strong></div></article>)}</div></div></section> }
